package asset

import (
	"time"

	"github.com/google/uuid"
)

// VariantType represents the type of asset variant generated by the system.
type VariantType string

const (
	Thumbnail VariantType = "thumbnail"
	Optimized VariantType = "optimized"
	WebP      VariantType = "webp"
	Preview   VariantType = "preview"
)

// Variant represents a generated version of an asset.
type Variant struct {
	ID          uuid.UUID
	AssetID     uuid.UUID
	Type        VariantType
	ContentType string
	Size        int64
	StoragePath string
	CreatedAt   time.Time
}
